import 'dart:convert';

class AWSQuestions {
  int index = 0;

  List questions = [
    json.decode('{"title":"Amazon S3 Usage","question":"What is the primary use of Amazon S3 in AWS?","possible_answers":{"A":"To manage relational databases","B":"To host static websites","C":"To execute code without provisioning servers","D":"To configure automatic scaling and load balancing"},"answer_percentages":{"A":10.0,"B":70.0,"C":10.0,"D":10.0},"right_answer":"B","topic_name":"Amazon S3","description_and_explanation":"Amazon S3 (Simple Storage Service) is an object storage service that offers industry-leading scalability, data availability, security, and performance. This makes it perfect for hosting static websites as it can store and retrieve any amount of data at any time from anywhere on the web.","difficulty_level":"Easy","pro_tip":"Use S3 to host static resources for web applications, such as HTML files, CSS files, and images.","fun_fact":"S3 was designed to provide 99.999999999% (11 9\'s) durability over a given year."}'),
    json.decode('{"title":"Deploying Containerized Applications","question":"Which AWS service is best suited for deploying a containerized application?","possible_answers":{"A":"AWS Lambda","B":"Amazon EC2","C":"Amazon ECS","D":"AWS Elastic Beanstalk"},"answer_percentages":{"A":5.0,"B":20.0,"C":65.0,"D":10.0},"right_answer":"C","topic_name":"Amazon ECS","description_and_explanation":"Amazon ECS (Elastic Container Service) is a highly scalable, high-performance container management service that supports Docker containers and allows you to easily run applications on a managed cluster of Amazon EC2 instances.","difficulty_level":"Medium","pro_tip":"Use ECS to manage complex applications that require fine-grained control over networking, security, and scaling.","fun_fact":"ECS supports Docker containers, which have become a standard for packaging and deploying applications."}'),
    json.decode('{"title":"Managing Infrastructure with AWS","question":"What AWS tool allows you to manage infrastructure as code?","possible_answers":{"A":"Amazon EC2","B":"AWS CloudFormation","C":"AWS CodeDeploy","D":"Amazon RDS"},"answer_percentages":{"A":5.0,"B":80.0,"C":10.0,"D":5.0},"right_answer":"B","topic_name":"AWS CloudFormation","description_and_explanation":"AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment. CloudFormation allows you to use programming languages or a simple text file to model and provision, in an automated and secure manner, all the resources needed for your applications across all regions and accounts.","difficulty_level":"Medium","pro_tip":"Utilize CloudFormation templates to automate the deployment and management of AWS resources, ensuring consistent environments every time.","fun_fact":"CloudFormation was one of the first AWS services to support YAML in addition to JSON for defining templates."}'),
    json.decode('{"title":"Data Warehousing with AWS","question":"Which service is primarily used for data warehousing in AWS?","possible_answers":{"A":"Amazon RDS","B":"Amazon Redshift","C":"AWS Data Pipeline","D":"Amazon S3"},"answer_percentages":{"A":10.0,"B":75.0,"C":5.0,"D":10.0},"right_answer":"B","topic_name":"Amazon Redshift","description_and_explanation":"Amazon Redshift is a fast, scalable data warehouse that makes it simple and cost-effective to analyze all your data across your data warehouses and data lakes. Redshift delivers ten times faster performance than other data warehouses by using machine learning, massively parallel query execution, and columnar storage on high-performance disk.","difficulty_level":"Hard","pro_tip":"Use Redshift for complex query processing over large sets of structured data for business intelligence and data analytics.","fun_fact":"Redshift is named after the astronomical phenomenon where light stretches into longer wavelengths as it moves away from the observer."}'),
    json.decode('{"title":"Global Content Delivery","question":"What feature in AWS allows you to deliver content globally with low latency?","possible_answers":{"A":"Amazon EC2 Auto Scaling","B":"AWS Direct Connect","C":"Amazon Route 53","D":"Amazon CloudFront"},"answer_percentages":{"A":10.0,"B":5.0,"C":15.0,"D":70.0},"right_answer":"D","topic_name":"Amazon CloudFront","description_and_explanation":"Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally with low latency, high transfer speeds, all within a developer-friendly environment.","difficulty_level":"Easy","pro_tip":"Integrate CloudFront with other AWS services such as S3, EC2, and Route 53 for enhanced performance and security of your applications.","fun_fact":"CloudFront\'s network has points of presence on all continents except Antarctica and is designed to offer developers and businesses an easy way to distribute content to end users with low latency and high data transfer speeds."}'),
    json.decode('{"title":"Kubernetes Management in AWS","question":"Which AWS service provides a managed Kubernetes service?","possible_answers":{"A":"Amazon EKS","B":"Amazon ECS","C":"AWS Lambda","D":"AWS Fargate"},"answer_percentages":{"A":85.0,"B":10.0,"C":0.0,"D":5.0},"right_answer":"A","topic_name":"Amazon EKS","description_and_explanation":"Amazon EKS (Elastic Kubernetes Service) is a managed service that makes it easy to deploy, manage, and scale containerized applications using Kubernetes on AWS. EKS integrates deeply with AWS services to provide a scalable and secure environment for your applications.","difficulty_level":"Medium","pro_tip":"Leverage EKS to simplify the management of Kubernetes clusters while utilizing AWS\'s scalability and security features.","fun_fact":"EKS automatically manages the availability and scalability of the Kubernetes control plane nodes, which is a key differentiator from self-managed Kubernetes setups."}'),
    json.decode('{"title":"Monitoring with CloudWatch","question":"What AWS service is used to monitor applications and resources?","possible_answers":{"A":"AWS CloudTrail","B":"Amazon CloudWatch","C":"AWS X-Ray","D":"AWS Shield"},"answer_percentages":{"A":10.0,"B":70.0,"C":15.0,"D":5.0},"right_answer":"B","topic_name":"Amazon CloudWatch","description_and_explanation":"Amazon CloudWatch is a monitoring and observability service built for DevOps engineers, developers, site reliability engineers (SREs), and IT managers. CloudWatch provides data and actionable insights to monitor your applications, respond to system-wide performance changes, and optimize resource utilization.","difficulty_level":"Easy","pro_tip":"Utilize CloudWatch alarms to automate scaling actions and to trigger notifications based on specific metrics thresholds.","fun_fact":"CloudWatch can collect monitoring data from all AWS resources and applications running on AWS and on-premises servers, providing a unified view of operational health."}'),
    json.decode('{"title":"Real-time Data Streaming with Kinesis","question":"Which AWS service is designed to handle real-time streaming data?","possible_answers":{"A":"Amazon Kinesis","B":"Amazon SQS","C":"Amazon S3","D":"AWS Glue"},"answer_percentages":{"A":75.0,"B":10.0,"C":5.0,"D":10.0},"right_answer":"A","topic_name":"Amazon Kinesis","description_and_explanation":"Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information. Kinesis provides key capabilities to cost-effectively process streaming data at any scale, along with the flexibility to choose the tools that best suit the needs of your application.","difficulty_level":"Medium","pro_tip":"Use Kinesis for applications that require real-time data processing such as log and event data collection, real-time analytics, and machine learning model inference.","fun_fact":"Kinesis is designed to process hundreds of terabytes per hour from high-volume sources such as operating logs, financial transactions, and social media feeds."}'),
    json.decode('{"title":"Event-driven Computing with Lambda","question":"What is the purpose of AWS Lambda?","possible_answers":{"A":"To provision virtual servers","B":"To automate software deployments","C":"To run code in response to events","D":"To manage database connections"},"answer_percentages":{"A":5.0,"B":10.0,"C":80.0,"D":5.0},"right_answer":"C","topic_name":"AWS Lambda","description_and_explanation":"AWS Lambda lets you run code without provisioning or managing servers. You pay only for the compute time you consume - there is no charge when your code is not running. You can run code for virtually any type of application or backend service - all with zero administration.","difficulty_level":"Easy","pro_tip":"Use Lambda to handle event-driven computing architectures, such as processing data streams, handling web requests, and updating databases.","fun_fact":"Lambda supports multiple programming languages, making it versatile for different coding environments and requirements."}'),
    json.decode('{"title":"Application Deployment with Elastic Beanstalk","question":"Which AWS service helps in deploying applications?","possible_answers":{"A":"AWS Elastic Beanstalk","B":"Amazon EC2","C":"Amazon ECS","D":"AWS OpsWorks"},"answer_percentages":{"A":75.0,"B":10.0,"C":10.0,"D":5.0},"right_answer":"A","topic_name":"AWS Elastic Beanstalk","description_and_explanation":"AWS Elastic Beanstalk is an easy-to-use service for deploying and scaling web applications and services developed with Java, .NET, PHP, Node.js, Python, Ruby, Go, and Docker on familiar servers such as Apache, Nginx, Passenger, and IIS. You simply upload your code and Elastic Beanstalk automatically handles the deployment, from capacity provisioning, load balancing, and auto-scaling to application health monitoring.","difficulty_level":"Easy","pro_tip":"Utilize Elastic Beanstalk for managing application deployments without worrying about the infrastructure.","fun_fact":"Elastic Beanstalk was one of the first cloud deployment services that provided an easy way for developers to deploy applications without the complexity of managing the infrastructure."}'),
    json.decode('{"title":"Network Isolation with Amazon VPC","question":"What AWS technology is used to create a logically isolated section of the Amazon Web Services cloud?","possible_answers":{"A":"Amazon VPC","B":"AWS Direct Connect","C":"Amazon EC2","D":"AWS IAM"},"answer_percentages":{"A":90.0,"B":5.0,"C":0.0,"D":5.0},"right_answer":"A","topic_name":"Amazon VPC","description_and_explanation":"Amazon VPC (Virtual Private Cloud) lets you provision a logically isolated section of the AWS cloud where you can launch AWS resources in a virtual network that you define. This gives you complete control over your virtual networking environment, including selection of your own IP address range, creation of subnets, and configuration of route tables and network gateways.","difficulty_level":"Medium","pro_tip":"Use VPC to enhance the security of your AWS resources by controlling the network access to and from your instances.","fun_fact":"The concept of VPC was introduced to provide enhanced security and customization options for more complex networking scenarios."}'),
    json.decode('{"title":"Dedicated Network Connection with AWS Direct Connect","question":"Which service within AWS provides a dedicated network connection from an on-premises to Amazon VPC?","possible_answers":{"A":"AWS Direct Connect","B":"Amazon Route 53","C":"Amazon EC2","D":"AWS Transit Gateway"},"answer_percentages":{"A":85.0,"B":5.0,"C":5.0,"D":5.0},"right_answer":"A","topic_name":"AWS Direct Connect","description_and_explanation":"AWS Direct Connect makes it easy to establish a dedicated network connection from your premises to AWS. This can reduce your network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.","difficulty_level":"Hard","pro_tip":"Opt for AWS Direct Connect for high-performance and secure data transfer needs between your data center and AWS.","fun_fact":"Direct Connect provides a dedicated link with a speed of up to 100 Gbps, facilitating large data transfers such as high-volume e-commerce sites and data migration projects."}')
];

  AWSQuestions._privateConstructor();
  static final AWSQuestions _instance = AWSQuestions._privateConstructor();

  factory AWSQuestions() {
    return _instance;
  }

  getNextQuestion() {
    index = (index == questions.length - 1) ? 0 : index + 1;
    return questions[index];
  }

  getNextQuestionsList(int count) {
    index = (index == questions.length - 1) ? 0 : index + 1;
    var questionsList = [];
    for(int i = index; i < count; i ++) {
      questionsList.add(questions[index]);
      index = (index == questions.length - 1) ? 0 : index + 1;
    }
    return questionsList;
  }
}