name: nerd_nudge
description: "A new way of learning and retaining what is learnt. Master Tech Concepts. Retain What Matters."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+42

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^2.0.0
  linear_timer: ^2.0.0
  mrx_charts: ^0.1.3
  fl_chart: ^0.68.0
  load_switch: ^2.1.0
  intl: ^0.19.0
  flutter_heatmap_calendar: ^1.0.5
  path_provider: ^2.0.9
  flutter_markdown: ^0.7.3
  animated_segmented_tab_control: ^2.0.0
  font_awesome_flutter: ^10.1.0
  share_plus: ^4.0.9

  cupertino_icons: ^1.0.6
  firebase_core: ^2.4.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  flutter_card_swiper: ^7.0.1
  http: ^0.13.3
  syncfusion_flutter_gauges: ^20.2.41
  rename: ^3.0.2
  purchases_flutter: ^8.1.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.9
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - images/


#flutter_icons:
#  android: true
#  ios: true
#  image_path: "images/app_logo_black_bg_1024.jpg"
#  adaptive_icon_background: "#000000"
#  adaptive_icon_foreground: "images/app_logo_black_bg_1024.png"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_logo_black_bg_1024.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/app_logo_black_bg_1024.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff" # Background color for splash screen
  image: assets/splash_logo.png # Path to your splash logo
  android_gravity: center # Ensures proper placement of the logo