// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoBYpimuAlUJYXHvSWVJEl7yaXX5wCAs',
    appId: '1:566821895818:web:2870a0c5c3a77857687773',
    messagingSenderId: '566821895818',
    projectId: 'nerdnudgetest',
    authDomain: 'nerdnudgetest.firebaseapp.com',
    storageBucket: 'nerdnudgetest.appspot.com',
    measurementId: 'G-ZM4QZSD2YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFNpk2ErOPK_FFcg6dS3Of6OJIJph5PKU',
    appId: '1:566821895818:android:daa2596a9f1720b6687773',
    messagingSenderId: '566821895818',
    projectId: 'nerdnudgetest',
    storageBucket: 'nerdnudgetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjB1c9-vcM00olsuqsO_nFQ_j8nxnSyI',
    appId: '1:566821895818:ios:5866799048e483aa687773',
    messagingSenderId: '566821895818',
    projectId: 'nerdnudgetest',
    storageBucket: 'nerdnudgetest.appspot.com',
    iosBundleId: 'com.neurospark.nerdNudge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjB1c9-vcM00olsuqsO_nFQ_j8nxnSyI',
    appId: '1:566821895818:ios:5866799048e483aa687773',
    messagingSenderId: '566821895818',
    projectId: 'nerdnudgetest',
    storageBucket: 'nerdnudgetest.appspot.com',
    iosBundleId: 'com.neurospark.nerdNudge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBoBYpimuAlUJYXHvSWVJEl7yaXX5wCAs',
    appId: '1:566821895818:web:0e8145be1fa5e780687773',
    messagingSenderId: '566821895818',
    projectId: 'nerdnudgetest',
    authDomain: 'nerdnudgetest.firebaseapp.com',
    storageBucket: 'nerdnudgetest.appspot.com',
    measurementId: 'G-74HJD5KD77',
  );
}
